stages:
  train_model:
    cmd: python pipeline/train_model.py data/processed/train_processed.csv models/catboost_model.cbm
    deps:
    - data/processed/train_processed.csv
    - src/features/build_features.py
    - src/models/train_model.py
    outs:
    - models/catboost_model.cbmQ
  preprocess:
    cmd: python pipeline/preprocess.py data/raw/train.csv data/processed/train_processed.csv
    deps:
    - data/raw/train.csv
    - pipeline/preprocess.py
    outs:
    - data/processed/train_processed.csv
